services:
  db:
    image: postgres:16
    container_name: clinic_db
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: clinic_user
      POSTGRES_PASSWORD: clinic_pass
    ports:
      - "5432:5432"
    volumes:
      - clinic_pgdata:/var/lib/postgresql/data

volumes:
  clinic_pgdata:
